# Generated by Django 5.2.6 on 2025-09-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dp_id', models.CharField(max_length=20)),
                ('boid', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('crn', models.CharField(max_length=20)),
                ('lot_size', models.IntegerField(default=10)),
            ],
        ),
    ]
